# Generated by Django 4.2.3 on 2024-02-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi_familyasi', models.CharField(max_length=200)),
                ('malumoti', models.TextField()),
                ('rasm', models.ImageField(upload_to='news/images')),
            ],
        ),
    ]
