# Generated by Django 4.2.3 on 2024-02-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_oqituvchilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='news/images')),
            ],
        ),
    ]
