# Generated by Django 4.2.3 on 2024-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_musoboqa_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tel_raqam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telfon', models.IntegerField()),
            ],
        ),
    ]
