# Generated by Django 4.2.3 on 2024-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tel_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel_raqam',
            name='telfon',
            field=models.CharField(max_length=100),
        ),
    ]
